testUrl=https://tutorialsninja.com/demo/
browserName=firefox
firstName=preeti
lastName=mishra
validPassword=1235
invalidPassword=1228
telephoneNumber=2389478
invalidemailone=amotoori
invalidemailtwo=amotoori@
invalidemailthree=amotoori@gmail
invalidemailfour=amotoori@gmail.
invalidTelephone=1abcde
spaceKeyInputs=        